### PR TITLE
Better collision resolution

### PR DESCRIPTION
**Pull request by fasky**
- asteroids look like they fly away when hit with bullet. Take other asteroids they hit with them. Varying positioning for asteroids.

### CODE REVIEW

**Comment by louisgv** [comment]
From the code, it seems you spawn a "Rock" object that acts very similar to a bullet, however the start-pos and end-pos seems a bit confusing to me:
```
pFlyaway->m_v3StartPos = pEnt->GetRigidBody()->GetCenterGlobal();
pFlyaway->m_v3EndPos = m_pFlyaways[h]->m_v3EndPos * 2;
```

The endpos is itself * 2, was the endpos ever initialized? I tried looking for it but doesn't see anything related :-? ...

**Comment by fasky** [comment]
That specific line is for setting the endpoint of a new flyaway rock that's spawned when a rock that's already flying away hits the original asteroid. It's not itself * 2 but the one that hit it's endpoint * 2. 

Also the direction they fly isn't perfect but it's something. You can try and make them fly away nicer or just submit it since that's all we had to change.

**Comment by louisgv** [comment]
@fasky  I made it scatter a bit based on the projectile and the rock itself. The Chain reaction is more chaos now which might be interesting?..

**Comment by fasky** [comment]
Yeah I think it's good. Hopefully that's good enough for him. It's better than disappearing right away.

**Review by louisgv — APPROVED** [review]
LGTM

**Pull request merged**
